// Code generated by MockGen. DO NOT EDIT.
// Source: url.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/amberdance/url-shortener/internal/domain/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockURLRepository) Create(ctx context.Context, url *model.URLEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, url)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockURLRepositoryMockRecorder) Create(ctx, url interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockURLRepository)(nil).Create), ctx, url)
}

// CreateBatch mocks base method.
func (m *MockURLRepository) CreateBatch(ctx context.Context, urls []*model.URLEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBatch", ctx, urls)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBatch indicates an expected call of CreateBatch.
func (mr *MockURLRepositoryMockRecorder) CreateBatch(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBatch", reflect.TypeOf((*MockURLRepository)(nil).CreateBatch), ctx, urls)
}

// DeleteByUserIDAndHashes mocks base method.
func (m *MockURLRepository) DeleteByUserIDAndHashes(ctx context.Context, userID uuid.UUID, hashes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndHashes", ctx, userID, hashes)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndHashes indicates an expected call of DeleteByUserIDAndHashes.
func (mr *MockURLRepositoryMockRecorder) DeleteByUserIDAndHashes(ctx, userID, hashes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndHashes", reflect.TypeOf((*MockURLRepository)(nil).DeleteByUserIDAndHashes), ctx, userID, hashes)
}

// FindAllByUserID mocks base method.
func (m *MockURLRepository) FindAllByUserID(ctx context.Context, userID uuid.UUID) ([]*model.URLEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.URLEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserID indicates an expected call of FindAllByUserID.
func (mr *MockURLRepositoryMockRecorder) FindAllByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserID", reflect.TypeOf((*MockURLRepository)(nil).FindAllByUserID), ctx, userID)
}

// FindByHash mocks base method.
func (m *MockURLRepository) FindByHash(ctx context.Context, hash string) (*model.URLEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(*model.URLEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockURLRepositoryMockRecorder) FindByHash(ctx, hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockURLRepository)(nil).FindByHash), ctx, hash)
}

// FindByOriginalURL mocks base method.
func (m *MockURLRepository) FindByOriginalURL(ctx context.Context, originalURL string) (*model.URLEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOriginalURL", ctx, originalURL)
	ret0, _ := ret[0].(*model.URLEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOriginalURL indicates an expected call of FindByOriginalURL.
func (mr *MockURLRepositoryMockRecorder) FindByOriginalURL(ctx, originalURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOriginalURL", reflect.TypeOf((*MockURLRepository)(nil).FindByOriginalURL), ctx, originalURL)
}
